# Generated by Django 4.0.4 on 2022-05-18 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_authors_alter_book_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(default='0000'),
            preserve_default=False,
        ),
    ]
