# Generated by Django 4.0.4 on 2022-05-18 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_authors_alter_book_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.TextField(default=''),
        ),
    ]
