# Generated by Django 4.0.4 on 2022-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=120)),
                ('authors', models.CharField(max_length=120)),
                ('published_year', models.CharField(max_length=4)),
                ('acquired', models.BooleanField(default=False)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
