# Generated by Django 4.0.4 on 2022-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.TextField()),
                ('title', models.CharField(max_length=120)),
                ('authors', models.CharField(max_length=120)),
                ('published_year', models.CharField(max_length=4)),
                ('acquired', models.BooleanField(default=False)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
