# Generated by Django 4.0.4 on 2022-05-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.DateField(max_length=4),
        ),
    ]
