# Generated by Django 4.0.4 on 2022-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_authors_alter_book_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.CharField(max_length=4),
        ),
    ]
